### ISSUE TITLE
Colon in value breaks stylesheet

### ISSUE THREAD

**Issue by lastw** [vkalinichev/postcss-rtl#10]
For example,

```
div { 
    background: url('http://placecage.com/400/400') 0 0 
}
```

transforms to

```
[dir=ltr] div {
    background: url('http://placecage.com/400/400') 0 0
} 

[dir=rtl] div { 
    background: url('http 
}
```

RTL-ed value is splitted by `:`

**Comment by vkalinichev** [comment]
Will fixed in the next release. Thanks for the report!

**Comment by lastw** [comment]
Nice!

No need for PR? I've fixed that too — https://github.com/lastw/postcss-rtl/tree/colons-in-value :)

**Comment by vkalinichev** [comment]
I will be glad to take this PR
