### ISSUE TITLE
I wanna use this plugin with Laravel mix

### ISSUE THREAD

**Issue by chadidi** [vkalinichev/postcss-rtl#12]
Can you help me out with this i wanna compile a scss file than make two files from the first file both will be saved in diffrent paths .

**Comment by vkalinichev** [comment]
Do you mean one file for ltr and second for rtl? Then you need [RTLCSS](https://github.com/MohammadYounes/rtlcss).

PostCSS-RTL about combining two-directional styles in single file.

**Comment by chadidi** [comment]
@vkalinichev  Yes this is it . one last question how can i use rtlcss with postcss cause i am just one day with postcss world ?

**Comment by vkalinichev** [comment]
As I know RTLCSS it's just a regular PostCSS plugin. So you can try something like this:
```
postcss([ require('rtlcss') ])
```
See [PostCSS usage guide](https://github.com/postcss/postcss#usage) for details
