### ISSUE TITLE
Unnecessary duplication of CSS declarations and rules

### ISSUE THREAD

**Issue by rolfen** [vkalinichev/postcss-rtl#24]
This is extracted from your example, in the Readme:

**Input**

```
.foo {
    (...)
    font-size: 13px;
    border-color: lightgray;
    (...)
```

**Output**

```
.foo {
    font-size: 13px
}

[dir] .foo {
    border-color: lightgray
}
```

I ran a test with default options, and also saw this in my CSS:

**Input**

```
#cart-button.hidden {
	display: none !important;
}
```

**Output**

```
[dir=ltr] #cart-button.hidden {
	display: none !important;
}

[dir=rtl] #cart-button.hidden {
	display:none !important;
}
```

A single declaration block has been turned into two, and the display property has been duplicated in the second example, for no obvious reason. As far as I can see, it will only raise file size, potentially introduce confusion and specificity problems.

Some rules are left as, some rules are split (prefixed with `[dir]`) and some are duplicated as above. I find this behavior hard to understand and predict.

For example, I cannot understand why `border-color` in your example would be put in a different rule with a prefixed selector.

`display` is not a directional rule either, there is no need to move it to `[rtl=...]` declarations.

This behavior should be consistent and understandable, maybe documented, if there is a logic.

Ideally rules should only be duplicated when necessary, as much as possible (only margin-left/right, or compound margin declarations, etc. - not margin-top, or border-color, for example).

**Comment by vkalinichev** [comment]
Fixed in `1.2.2`. Thanks for report!
