### ISSUE TITLE
PostCSS-RTL + Angular Encapsulated Styles

### ISSUE THREAD

**Issue by eLaLaN** [vkalinichev/postcss-rtl#38]
The [dir] attribute prefix that postcss-rtl adds is being suffixed with the _ngcontent-X selector.

Current output
    [dir][_ngcontent-c1]   .make-request-container[_ngcontent-c1]   .category[_ngcontent-c1] 

Expected Output
    [dir] .make-request-container[_ngcontent-c1]   .category[_ngcontent-c1] 

I'm importing postcss-rtl into my webpack config, and calling it as last plugin of the 'postcss-loader'

**Comment by vkalinichev** [comment]
Thanks for report. I try to fix it in the next release.

**Comment by vkalinichev** [comment]
Cannot reproduce yet. Can you provide original css rule and postcss-part of webpack config?

**Comment by redaxmedia** [comment]
@eLaLaN Can't you fix this using :host::ng-deep or something like that?
