### ISSUE TITLE
rtlcss-directives

### ISSUE THREAD

**Issue by jonnitto** [vkalinichev/postcss-rtl#5]
Is there a roadmap/timeplan for the rtlcss-directives?

**Comment by derzunov** [comment]
+1

**Comment by vkalinichev** [comment]
I plan to implement this in the near future (march-april).

I will be glad to accept help!

**Comment by joscha** [comment]
at which point do 
```
/* rtl:begin:ignore */
.bla { margin-left: 0; }
/* rtl:end:ignore */

/* rtl:ignore */ .bla2 { margin-left: 0; }
```

get lost?

I tried prefixing them with `!` to get them past [cssnano](http://cssnano.co/optimisations/discardcomments/), but postcss-rtl still seems to ignore them.

**Comment by vkalinichev** [comment]
Directives of rtlcss (including `rtl:ignore`) is not supported. Yet. The subj is just about that.

Unfortunately, I do not have time for OSS projects lately and I don't know when I resume work.

**Comment by joscha** [comment]
Please have a look at #16
