### ISSUE TITLE
version ^1.6 fails on between.match

### ISSUE THREAD

**Issue by danarish4** [vkalinichev/postcss-rtl#59]
Hey, from version 1.6 and up our build is failing with this error. 
![image](https://user-images.githubusercontent.com/45333005/74834176-952df800-5323-11ea-8fed-c71a69b56d5a.png)

You can see it fail in this project if you update postcss-rtl version in package json
https://github.com/wix-incubator/rich-content

**Comment by vkalinichev** [comment]
Fixed in `1.7.2`

Thanks for report!
