### ISSUE TITLE
Handle rules applyed to <html>

### ISSUE THREAD

**Issue by rformato** [vkalinichev/postcss-rtl#6]
Is there a way to handle css rules applyed to the `<html>` element?

A common example is handling rules whose selector is a class added by Detectirz on the html element, such as `.tablet`.

Such a rule will be transformed in `[dir="ltr"] .tablet` ... which is not right

**Comment by rformato** [comment]
Using `html.tablet` fixes the issue, which is acceptable, even if at first it was not obvious to me

**Comment by vkalinichev** [comment]
You can add `addPrefixToSelector` parameter to your config:

```js
const postcss = require( 'postcss' )

const rtl = require( 'postcss-rtl' )( {
  addPrefixToSelector: function (selector, prefix) {
    if ( /^\.tablet/.test( selector ) ) {
      return selector.replace( /^\.tablet/, `.tablet${prefix}` )
    }
    return `${prefix} ${selector}`
  }
} )
```

But I recommend to explicitly define root elements like `html.tablet` or `:root.tablet`
