### ISSUE TITLE
question: why do i need to use this plugin (which uses rtlcss under the hood) instead rtlcss itself, when rtlcss is working with postcss out of the box?

### ISSUE THREAD

**Issue by iamstarkov** [vkalinichev/postcss-rtl#7]
first of all, thanks for this plugin. I understand how hard it can be to maintain oss project. that said, im here not to blame but clear out some confusion. 

I looked into postcss plugins list and there are two rtl related packages: [postcss-rtl][] (this one) and [rtlcss][]. it confuses a bit. then i figured as well that this plugin uses rtlcss under the hood. After reading rtlcss's usage [instructions][] its clear you can use rtlcss as ordinary postcss plugin:

```js
var result = postcss().use(rtlcss([options , plugins]))
                      .use(autoprefixer())
                      .process(css);
```

My question is: why do i need to use this plugin over vanilla rtlcss itself, when rtlcss is working with postcss out of the box?

PS. After some digging, it seems like rtlcss flips your css completely, while postcss-rtl outputs both ltr and rtl layouts. is it a reason and the only differencse?

[postcss-rtl]: https://github.com/vkalinichev/postcss-rtl/
[rtlcss]: https://github.com/MohammadYounes/rtlcss
[instructions]: http://rtlcss.com/learn/usage-guide/install/

**Comment by vkalinichev** [comment]
> it seems like rtlcss flips your css completely, while postcss-rtl outputs both ltr and rtl layouts. is it a reason and the only differencse?

**Yes, that's the reason**.

I think in most cases using two copies of direction-separated styles is overhead.

**Comment by iamstarkov** [comment]
Thanks
