### ISSUE TITLE
Cannot read property 'unprefixed' of undefined

### ISSUE THREAD

**Issue by ghost** [vkalinichev/postcss-rtl#76]
...
 "postcss": "^8.2.4",
    "postcss-cli": "^8.3.1",
    "postcss-rtl": "^1.7.3"
...

postcss.vendor has been removed in PostCSS 8

please support it

**Comment by crown-li** [comment]
I had the same problem，Is there any solution?

**Comment by fabercancio** [comment]
I couldn't use PostCSS 8 because of this but with PostCSS 7 this issue doesn't exist.

**Comment by GeromeF** [comment]
Hello,
same problem here, did someone find a way to solve that ??
What is the right config in package.json ??

**Comment by fabercancio** [comment]
Hi @GeromeF, we didn't find a solution for this. As this repo is no longer maintained, we've migrated to [postcss-rtlcss](https://github.com/elchininet/postcss-rtlcss), as it also uses rtlcss, the migration was straightforward and excepting an issue that we are having with the values of the variables that are not being flipped, it works perfectly.

**Comment by fabercancio** [comment]
If someone wants to solve this with this package, [here](https://github.com/vkalinichev/postcss-rtl/pull/73) you can find a pull request and a forked package that solves this issue.
